name: Discord notification
on: [push] # or any other trigger event you'd like
jobs:
    send-notification:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Get commit changes
              id: commit_changes
              run: |
                  # Fetch commit information using GitHub API
                  commit_date=$(curl --silent --location --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.after }}" \
                    | jq -r '.commit.committer.date')
                  human_readable_date=$(TZ="America/Los_Angeles" date -d"$commit_date" +"%B %d, %Y %I:%M %p %Z")
                  lines_added=$(curl --silent --location --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.after }}" \
                    | jq -r '.files | map(select(.filename | test(".cs$"))) | map(.additions) | add')
                  lines_deleted=$(curl --silent --location --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.after }}" \
                    | jq -r '.files | map(select(.filename | test(".cs$"))) | map(.deletions) | add')
                  echo "human_readable_date=$human_readable_date" >> $GITHUB_ENV
                  echo "lines_added=$lines_added" >> $GITHUB_ENV
                  echo "lines_deleted=$lines_deleted" >> $GITHUB_ENV

            - name: Discord notification
              if: "env.lines_added != 'null' || env.lines_deleted != 'null'"
              uses: Ilshidur/action-discord@master
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
              with:
                  args: >

                      ---

                      >>> **New Commit!**

                      ${{ github.event.head_commit.message }} 

                      ---

                      Lines added: **+${{ env.lines_added }}**

                      Lines deleted: **-${{ env.lines_deleted }}**

                      Date: ${{ env.human_readable_date }}

                      Link: 

                      ${{ github.event.head_commit.url }}
