name: "Discord Notification"
description: "Send a Discord notification for new commits on C# files"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
  DISCORD_WEBHOOK:
    description: "Discord webhook URL"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16"
    - run: npm ci
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: node ${{ github.action_path }}/main.js
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        DISCORD_WEBHOOK: ${{ inputs.DISCORD_WEBHOOK }}
